### ISSUE TITLE
Psalter support?

### ISSUE THREAD

**Issue by kkmuffme** [orklah/psalm-strict-equality#2]
Are these issues auto-fixable?

Atm I get:
>Psalm doesn't know how to fix issue(s): NotStrictEqualSign

**Comment by orklah** [comment]
Yeah they are, but Psalm does not allow plugin to register fixable issues like that.

Technically, as long as you are in psalter mode, this plugin should start fixing issue, so if you try to fix another issue, this will get fixed along the way. Otherwise, if you only want to fix this issue, the command should look like `vendor/bin/psalm --alter --plugin=vendor/orklah/psalm-strict-equality/src/Plugin.php`

This should be improved in Psalm itself but I couldn't find time to do that
